/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.borwe.system.gc;

import java.lang.instrument.Instrumentation;

public class App {
	
	public static void premain(String agentArgs,Instrumentation inst) {
        beginGCThread();
	}

	public static void agentmain(String agentArgs,Instrumentation inst) {
        beginGCThread();
	}
	
    private static void beginGCThread(){
		Thread thread=new Thread(()->{
            //sleep for 5 minutes, before starting the GC stuff
			while(true) {
				try {
					Thread.sleep(1002);
					System.gc();
					//System.out.println("GC HAPPENED");
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		});
		thread.setDaemon(true);
		thread.start();
    }
}
