/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.borwe.system.gc;

import java.lang.instrument.Instrumentation;

public class App {
	
	
	public static void premain(String agentArgs,Instrumentation inst) {
		System.out.println("Using Premain GC");
//		getAllClassesAndSetupGC(agentArgs, inst);
        beginGCThread();
	}

	public static void agentmain(String agentArgs,Instrumentation inst) {
		System.out.println("Using Agentmain GC");
        beginGCThread();
	}
	
    private static void beginGCThread(){
		var thread=new Thread(()->{
			while(true) {
				try {
					Thread.sleep(1002);
					System.gc();
					//System.out.println("GC HAPPENED");
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		});
		thread.setDaemon(true);
		thread.start();
    }
}
